version: '3.0'

services:
  map:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:8000
    volumes:
#      - ./logs:/web/logs
      - ./data:/app/data